### ISSUE TITLE
Issues with suggestion's display UI

### ISSUE THREAD

**Issue by idcuesta** [ppaulojr/PPJEmailPicker#10]
## Description

There are some issues around suggestion's tableview:
- [x] When text is cleared, suggestions for previous text are not cleared.
- [x] When text doesn't match any suggestion, tableview is not displaying any row but it doesn't resize.
- [x] When text doesn't match any suggestion, and a character is deleted so it should find suggestions, tableview is not displaying them.
## Screenshot

![not-resizing-after-table-content-change](https://cloud.githubusercontent.com/assets/2726409/15533315/113d6324-225c-11e6-81dc-c80584fd97be.gif)

**Comment by ppaulojr** [comment]
Thanks @idcuesta !
