### ISSUE TITLE
Deleting after having selected a selected email deletes text and not the email

### ISSUE THREAD

**Issue by idcuesta** [ppaulojr/PPJEmailPicker#13]
## Description

If there is any previously selected email, and user is editing a new one, when user highlight the selected email and press delete key, current text's last character is deleted and not the highlighted email.
## Screenshot

![deleting-from-emaillabel-when-editing-deletes-text](https://cloud.githubusercontent.com/assets/2726409/15534426/9f366fdc-2260-11e6-9bd1-0c6d6a055450.gif)

**Comment by ppaulojr** [comment]
Thanks!
