### ISSUE TITLE
Cursor sometimes in the wrong position

### ISSUE THREAD

**Issue by ppaulojr** [ppaulojr/PPJEmailPicker#3]
Add and delete emails. Notice the cursor position.

**Comment by idcuesta** [comment]
I think this one is caused by the component not forcing layout subviews after deleting an email label

## Screenshot

![deleting-ui-glitch](https://cloud.githubusercontent.com/assets/2726409/15533494/c3e3443a-225c-11e6-8bab-505d24a73d07.gif)

**Comment by idcuesta** [comment]
Probably related, when deleting a selected email the component is not refreshing the layout

## Screenshot

![deleting-email-label-dont-relayout](https://cloud.githubusercontent.com/assets/2726409/15534137/5cff5328-225f-11e6-95f8-9a63e77772e6.gif)

**Comment by ppaulojr** [comment]
Thanks @idcuesta! Fixed.
